LURE: Convert printf to debug/warning
Exception: The "decompiler" code still uses fopen/fprintf etc.
but it is disabled by default, hence I am ignoring it for now.

svn-id: r54108